-- Create equipment/listings table for heavy machinery inventory
create table "public"."equipment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    
    -- Auto-generated fields
    "stock_number" text generated always as ('EQ' || lpad(id::text, 6, '0')) stored,
    
    -- Basic equipment information
    "manufacturer" text not null,
    "model" text not null,
    "year" smallint,
    "condition" text,
    "serial_number" text,
    "hours" integer,
    
    -- Categorization
    "category" text,
    "subcategories" text[],
    "listing_type" text default 'Regular',
    
    -- Location and pricing
    "location" text,
    "price" numeric(12, 2),
    "quantity" integer default 1,
    
    -- Descriptions and notes
    "description" text,
    "private_notes" text,
    "import_notes" text,
    
    -- Images and documents (stored as JSON arrays with URLs)
    "images" jsonb default '[]'::jsonb,
    "public_documents" jsonb default '[]'::jsonb,
    "private_documents" jsonb default '[]'::jsonb,
    
    -- Status and features
    "status" text default 'available',
    "featured" boolean default false,
    
    -- Relationships
    "sales_id" bigint,
    "default_sales_rep_id" bigint
);

-- Enable RLS
alter table "public"."equipment" enable row level security;

-- Add primary key
alter table "public"."equipment" add constraint "equipment_pkey" primary key ("id");

-- Add foreign keys
alter table "public"."equipment" 
    add constraint "equipment_sales_id_fkey" 
    foreign key ("sales_id") 
    references "public"."sales"("id") 
    on delete set null;

alter table "public"."equipment" 
    add constraint "equipment_default_sales_rep_id_fkey" 
    foreign key ("default_sales_rep_id") 
    references "public"."sales"("id") 
    on delete set null;

-- Create indexes for common queries
create index "equipment_manufacturer_idx" on "public"."equipment"("manufacturer");
create index "equipment_category_idx" on "public"."equipment"("category");
create index "equipment_status_idx" on "public"."equipment"("status");
create index "equipment_sales_id_idx" on "public"."equipment"("sales_id");
create index "equipment_created_at_idx" on "public"."equipment"("created_at" desc);

-- Add updated_at trigger
create or replace function update_equipment_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger equipment_updated_at
    before update on "public"."equipment"
    for each row
    execute function update_equipment_updated_at();

-- Row Level Security Policies
-- All authenticated users can view equipment
create policy "Equipment visible to authenticated users"
    on "public"."equipment" for select
    to authenticated
    using (true);

-- Sales reps can insert equipment
create policy "Sales reps can create equipment"
    on "public"."equipment" for insert
    to authenticated
    with check (
        exists (
            select 1 from sales 
            where sales.user_id = auth.uid()
            and sales.disabled = false
        )
    );

-- Sales reps can update their own equipment or if they are admin
create policy "Sales reps can update own equipment"
    on "public"."equipment" for update
    to authenticated
    using (
        exists (
            select 1 from sales 
            where sales.user_id = auth.uid()
            and (
                sales.id = equipment.sales_id 
                or sales.id = equipment.default_sales_rep_id
                or sales.administrator = true
            )
        )
    );

-- Only admins can delete equipment
create policy "Admins can delete equipment"
    on "public"."equipment" for delete
    to authenticated
    using (
        exists (
            select 1 from sales 
            where sales.user_id = auth.uid()
            and sales.administrator = true
        )
    );

-- Create equipment_contacts junction table for many-to-many relationships
create table "public"."equipment_contacts" (
    "id" bigint generated by default as identity not null,
    "equipment_id" bigint not null,
    "contact_id" bigint not null,
    "interest_level" text,
    "notes" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."equipment_contacts" enable row level security;

alter table "public"."equipment_contacts" add constraint "equipment_contacts_pkey" primary key ("id");

alter table "public"."equipment_contacts" 
    add constraint "equipment_contacts_equipment_id_fkey" 
    foreign key ("equipment_id") 
    references "public"."equipment"("id") 
    on delete cascade;

alter table "public"."equipment_contacts" 
    add constraint "equipment_contacts_contact_id_fkey" 
    foreign key ("contact_id") 
    references "public"."contacts"("id") 
    on delete cascade;

-- Unique constraint to prevent duplicate relationships
alter table "public"."equipment_contacts" 
    add constraint "equipment_contacts_unique" 
    unique ("equipment_id", "contact_id");

create index "equipment_contacts_equipment_id_idx" on "public"."equipment_contacts"("equipment_id");
create index "equipment_contacts_contact_id_idx" on "public"."equipment_contacts"("contact_id");

-- RLS for equipment_contacts
create policy "Equipment contacts visible to authenticated users"
    on "public"."equipment_contacts" for select
    to authenticated
    using (true);

create policy "Sales reps can manage equipment contacts"
    on "public"."equipment_contacts" for all
    to authenticated
    using (
        exists (
            select 1 from sales 
            where sales.user_id = auth.uid()
            and sales.disabled = false
        )
    );
